import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopApi } from '../shared/models';

/** One explicit method per IPC channel; raw ipcRenderer is never exposed. */
const api: DesktopApi = {
  app: {
    version: () => ipcRenderer.invoke('app:version'),
    onNavigate: listener => {
      const handler = (_event: Electron.IpcRendererEvent, page: string) => {if(page==='inventory'||page==='reports')listener(page);};
      ipcRenderer.on('app:navigate',handler);
      return () => {ipcRenderer.removeListener('app:navigate',handler);};
    },
  },
  pos: {
    cartDraft: () => ipcRenderer.invoke('pos:cart-draft'),
    saveCartDraft: draft => ipcRenderer.invoke('pos:save-cart-draft',draft),
    capabilities: () => ipcRenderer.invoke('pos:capabilities'),
    setFeature: (name,enabled) => ipcRenderer.invoke('pos:set-feature',name,enabled),
    notificationPreferences: () => ipcRenderer.invoke('pos:notification-preferences'),
    saveNotificationPreferences: prefs => ipcRenderer.invoke('pos:save-notification-preferences',prefs),
    cartProducts: (ids) => ipcRenderer.invoke('pos:cart-products',ids),
    expenseCategories: () => ipcRenderer.invoke('pos:expense-categories'),
    removeExpense: (id) => ipcRenderer.invoke('pos:remove-expense',id),
    dashboard: () => ipcRenderer.invoke('pos:dashboard'),
    report: (from, to) => ipcRenderer.invoke('pos:report', from, to),
    reportAnalytics: (from, to) => ipcRenderer.invoke('pos:report-analytics', from, to),
    activity: () => ipcRenderer.invoke('pos:activity'),
    stockDiscrepancies: () => ipcRenderer.invoke('pos:stock-discrepancies'),
    crashes: () => ipcRenderer.invoke('pos:crashes'),
    logCrash: (message, source) => ipcRenderer.invoke('pos:log-crash', message, source),
    clearCrashes: () => ipcRenderer.invoke('pos:clear-crashes'),
    cashSessions: () => ipcRenderer.invoke('pos:cash-sessions'),
    paymentMethods: () => ipcRenderer.invoke('pos:payment-methods'),
    savePaymentMethod: (input) => ipcRenderer.invoke('pos:save-payment-method', input),
    removePaymentMethod: (id) => ipcRenderer.invoke('pos:remove-payment-method', id),
    priceLevels: () => ipcRenderer.invoke('pos:price-levels'),
    savePriceLevel: (input) => ipcRenderer.invoke('pos:save-price-level', input),
    removePriceLevel: (id) => ipcRenderer.invoke('pos:remove-price-level', id),
    productTiers: (productId) => ipcRenderer.invoke('pos:product-tiers', productId),
    saveProductTier: (input) => ipcRenderer.invoke('pos:save-product-tier', input),
    removeProductTier: (id) => ipcRenderer.invoke('pos:remove-product-tier', id),
    priceFor: (productId, priceLevelId, quantity) => ipcRenderer.invoke('pos:price-for', productId, priceLevelId, quantity),
    products: (search) => ipcRenderer.invoke('pos:products', search),
    productPage: (input) => ipcRenderer.invoke('pos:product-page', input),
    productSummary: () => ipcRenderer.invoke('pos:product-summary'),
    categoryProductCounts: () => ipcRenderer.invoke('pos:category-product-counts'),
    findByBarcode: (code) => ipcRenderer.invoke('pos:find-barcode', code),
    saveProduct: (input) => ipcRenderer.invoke('pos:save-product', input),
    removeProduct: (id) => ipcRenderer.invoke('pos:remove-product', id),
    categories: () => ipcRenderer.invoke('pos:categories'),
    saveCategory: (input) => ipcRenderer.invoke('pos:save-category', input),
    removeCategory: (id) => ipcRenderer.invoke('pos:remove-category', id),
    suppliers: (search) => ipcRenderer.invoke('pos:suppliers', search),
    saveSupplier: (input) => ipcRenderer.invoke('pos:save-supplier', input),
    removeSupplier: (id) => ipcRenderer.invoke('pos:remove-supplier', id),
    supplierPurchases: (supplierId, from, to) => ipcRenderer.invoke('pos:supplier-purchases', supplierId, from, to),
    supplierSpend: (supplierId, from, to) => ipcRenderer.invoke('pos:supplier-spend', supplierId, from, to),
    stockHistory: (productId) => ipcRenderer.invoke('pos:stock-history', productId),
    setStockTo: (productId, counted, reason) => ipcRenderer.invoke('pos:set-stock-to', productId, counted, reason),
    adjustStock: (productId, quantityDelta, type, reason, details) => ipcRenderer.invoke('pos:adjust-stock', productId, quantityDelta, type, reason, details),
    customers: () => ipcRenderer.invoke('pos:customers'),
    customerPage: (input) => ipcRenderer.invoke('pos:customer-page', input),
    customerSummary: () => ipcRenderer.invoke('pos:customer-summary'),
    saveCustomer: (input) => ipcRenderer.invoke('pos:save-customer', input),
    removeCustomer: (id) => ipcRenderer.invoke('pos:remove-customer', id),
    customerLedger: (id) => ipcRenderer.invoke('pos:customer-ledger', id),
    checkout: (draft) => ipcRenderer.invoke('pos:checkout', draft),
    sales: (search, from, to) => ipcRenderer.invoke('pos:sales', search, from, to),
    salesPage: (input) => ipcRenderer.invoke('pos:sales-page', input),
    salesSummary: (input) => ipcRenderer.invoke('pos:sales-summary', input),
    receipt: (voucherId) => ipcRenderer.invoke('pos:receipt', voucherId),
    returnableSale: (voucherId) => ipcRenderer.invoke('pos:returnable-sale', voucherId),
    returnSale: (voucherId, lines, refundMethod, note, amount) => ipcRenderer.invoke('pos:return-sale', voucherId, lines, refundMethod, note, amount),
    debtors: () => ipcRenderer.invoke('pos:debtors'),
    collectDebt: (customerId, amount, methodCode, note, saleId, paidAt) => ipcRenderer.invoke('pos:collect-debt', customerId, amount, methodCode, note, saleId, paidAt),
    cashSession: () => ipcRenderer.invoke('pos:cash-session'),
    openCashSession: (openingFloat) => ipcRenderer.invoke('pos:open-cash-session', openingFloat),
    closeCashSession: (countedCash) => ipcRenderer.invoke('pos:close-cash-session', countedCash),
    expenses: (from,to) => ipcRenderer.invoke('pos:expenses',from,to),
    saveExpense: (name, amount, note, details) => ipcRenderer.invoke('pos:save-expense', name, amount, note, details),
    shopProfile: () => ipcRenderer.invoke('pos:shop-profile'),
    saveShopProfile: (profile) => ipcRenderer.invoke('pos:save-shop-profile', profile),
  },
  cloud: {
    completeLogin: input => ipcRenderer.invoke('cloud:complete-login',input),
    join: input => ipcRenderer.invoke('cloud:join',input),
    createPairingCode: () => ipcRenderer.invoke('cloud:pairing-code'),
    confirmSwitch: () => ipcRenderer.invoke('cloud:confirm-switch'),
    cancelSwitch: () => ipcRenderer.invoke('cloud:cancel-switch'),
    submitSlip: input => ipcRenderer.invoke('cloud:submit-slip',input),
    listSlips: () => ipcRenderer.invoke('cloud:list-slips'),
    state: () => ipcRenderer.invoke('cloud:state'),
    setApiUrl: (url) => ipcRenderer.invoke('cloud:set-api-url', url),
    register: (input) => ipcRenderer.invoke('cloud:register', input),
    login: (input) => ipcRenderer.invoke('cloud:login', input),
    syncNow: () => ipcRenderer.invoke('cloud:sync-now'),
    signOut: () => ipcRenderer.invoke('cloud:sign-out'),
    rebuildLocalData: () => ipcRenderer.invoke('cloud:rebuild-local-data'),
    removeLocalData: () => ipcRenderer.invoke('cloud:remove-local-data'),
    deleteCloudAccount: input => ipcRenderer.invoke('cloud:delete-account', input),
    devices: () => ipcRenderer.invoke('cloud:devices'),
    revokeDevice: (id) => ipcRenderer.invoke('cloud:revoke-device', id),
    billingStatus: () => ipcRenderer.invoke('cloud:billing-status'),
    redeemCode: (code) => ipcRenderer.invoke('cloud:redeem-code', code),
    cashDrawers: () => ipcRenderer.invoke('cloud:cash-drawers'),
    createCashDrawer: (name) => ipcRenderer.invoke('cloud:create-cash-drawer', name),
    assignCashDrawer: (deviceId, drawerId, canManage) => ipcRenderer.invoke('cloud:assign-cash-drawer', deviceId, drawerId, canManage),
  },
  printer: {
    list: () => ipcRenderer.invoke('printer:list'),
    settings: () => ipcRenderer.invoke('printer:settings'),
    saveSettings: (settings) => ipcRenderer.invoke('printer:save-settings', settings),
    printReceipt: (receipt) => ipcRenderer.invoke('printer:print-receipt', receipt),
    test: () => ipcRenderer.invoke('printer:test'),
  },
};

contextBridge.exposeInMainWorld('storePos', api);
