const ERROR_MESSAGES: Record<string, string> = {
  'Product name and a non-negative price are required': 'ကုန်ပစ္စည်းအမည်နှင့် မှန်ကန်သောစျေးနှုန်း ထည့်ပါ။',
  'Product not found': 'ကုန်ပစ္စည်းကို မတွေ့ပါ။',
  'That barcode already belongs to a product': 'ဤဘားကုဒ်ကို အခြားကုန်ပစ္စည်းတစ်ခုတွင် အသုံးပြုထားပြီးဖြစ်သည်။',
  'Enter valid cost, minimum stock and quantity': 'ဝယ်ရင်းစျေး၊ အနည်းဆုံးလက်ကျန်နှင့် အရေအတွက်ကို မှန်ကန်စွာထည့်ပါ။',
  'Category name is required': 'အမျိုးအစားအမည် ထည့်ပါ။',
  'Category not found': 'အမျိုးအစားကို မတွေ့ပါ။',
  'Supplier name is required': 'ပေးသွင်းသူအမည် ထည့်ပါ။',
  'Supplier not found': 'ပေးသွင်းသူကို မတွေ့ပါ။',
  'Price level name is required': 'စျေးနှုန်းအဆင့်အမည် ထည့်ပါ။',
  'Price level not found': 'စျေးနှုန်းအဆင့်ကို မတွေ့ပါ။',
  'The default retail level cannot be removed': 'မူလလက်လီစျေးအဆင့်ကို ဖယ်ရှား၍မရပါ။',
  'Quantity and price must be positive': 'အရေအတွက်နှင့် စျေးနှုန်းသည် သုညထက်များရပါမည်။',
  'Price tier not found': 'အရေအတွက်လိုက်စျေးကို မတွေ့ပါ။',
  'Payment method name is required': 'ပေးချေမှုနည်းလမ်းအမည် ထည့်ပါ။',
  'Credit is an unpaid balance, not a payment method': 'အကြွေးသည် ပေးချေမှုနည်းလမ်းမဟုတ်ဘဲ မရှင်းရသေးသောလက်ကျန်ဖြစ်သည်။',
  'That payment method already exists': 'ဤပေးချေမှုနည်းလမ်း ရှိပြီးဖြစ်သည်။',
  'Payment method not found': 'ပေးချေမှုနည်းလမ်းကို မတွေ့ပါ။',
  'Counted stock cannot be negative': 'ရေတွက်ရရှိသော လက်ကျန်သည် အနုတ်မဖြစ်ရပါ။',
  'Invalid stock action': 'လက်ကျန်လုပ်ဆောင်ချက် မမှန်ပါ။',
  'Enter a non-zero stock quantity': 'သုညမဟုတ်သော လက်ကျန်အရေအတွက် ထည့်ပါ။',
  'Received stock must be positive': 'ကုန်ဝင်အရေအတွက်သည် သုညထက်များရပါမည်။',
  'Waste stock must be negative': 'ပျက်စီးဆုံးရှုံးမှုအရေအတွက်သည် အနုတ်ဖြစ်ရပါမည်။',
  'Selected supplier was not found': 'ရွေးထားသော ပေးသွင်းသူကို မတွေ့ပါ။',
  'Customer name is required': 'ဖောက်သည်အမည် ထည့်ပါ။',
  'Customer could not be saved': 'ဖောက်သည်အချက်အလက်ကို မသိမ်းနိုင်ပါ။',
  'Customer not found': 'ဖောက်သည်ကို မတွေ့ပါ။',
  'This customer still owes money': 'ဤဖောက်သည်တွင် အကြွေးကျန်ရှိနေသေးသည်။',
  'Add at least one product to the sale': 'အရောင်းထဲသို့ အနည်းဆုံး ကုန်ပစ္စည်းတစ်ခု ထည့်ပါ။',
  'Enter valid quantities, prices and discounts': 'အရေအတွက်၊ စျေးနှုန်းနှင့် လျှော့စျေးကို မှန်ကန်စွာထည့်ပါ။',
  'Payment amounts must be non-negative': 'ပေးချေငွေသည် အနုတ်မဖြစ်ရပါ။',
  'Cash received is less than the payment': 'လက်ခံရရှိသောငွေသားသည် ပေးချေရမည့်ငွေထက် နည်းနေသည်။',
  'Payments exceed the sale total': 'ပေးချေငွေသည် အရောင်းစုစုပေါင်းထက် များနေသည်။',
  'Choose a customer for the unpaid balance': 'ကျန်အကြွေးအတွက် ဖောက်သည်ရွေးပါ။',
  'That transaction cannot be returned': 'ဤအရောင်းကို ပြန်သွင်း၍မရပါ။',
  'Choose each return product once': 'ပြန်သွင်းမည့် ကုန်ပစ္စည်းတစ်ခုစီကို တစ်ကြိမ်သာ ရွေးပါ။',
  'That product is no longer returnable': 'ဤကုန်ပစ္စည်းကို ပြန်သွင်း၍မရတော့ပါ။',
  'Choose at least one item to return': 'ပြန်သွင်းရန် အနည်းဆုံး ပစ္စည်းတစ်ခုရွေးပါ။',
  'Refund must be between zero and the return value': 'ပြန်အမ်းငွေသည် သုညမှ ပြန်သွင်းတန်ဖိုးအတွင်း ဖြစ်ရပါမည်။',
  'A partial refund needs a customer to credit': 'တစ်စိတ်တစ်ပိုင်းပြန်အမ်းရန် ဖောက်သည်ရွေးပါ။',
  'Choose a valid report period': 'မှန်ကန်သော အစီရင်ခံကာလ ရွေးပါ။',
  'Collection amount must be more than zero': 'အကြွေးဆပ်ငွေသည် သုညထက်များရပါမည်။',
  'Sale not found for this customer': 'ဤဖောက်သည်၏ အရောင်းကို မတွေ့ပါ။',
  'Enter a non-negative opening float': 'အနုတ်မဟုတ်သော အဖွင့်ငွေ ထည့်ပါ။',
  'A till session is already open': 'ငွေစာရင်းပုံး ဖွင့်ထားပြီးဖြစ်သည်။',
  'No open till session': 'ဖွင့်ထားသော ငွေစာရင်းပုံး မရှိပါ။',
  'Counted cash is required': 'ရေတွက်ရရှိသောငွေ ထည့်ပါ။',
  'Expense name and positive amount are required': 'အသုံးစရိတ်အမည်နှင့် မှန်ကန်သောငွေပမာဏ ထည့်ပါ။',
  'Expense not found': 'အသုံးစရိတ်ကို မတွေ့ပါ။',
  'Choose an active payment method': 'အသုံးပြုနေသော ပေးချေမှုနည်းလမ်းတစ်ခု ရွေးပါ။',
  'Only the owner can change shop features': 'ဆိုင်ပိုင်ရှင်သာ ဆိုင်လုပ်ဆောင်ချက်များကို ပြောင်းနိုင်သည်။',
  'Only the owner can configure reminders': 'ဆိုင်ပိုင်ရှင်သာ သတိပေးချက်ကို ပြင်နိုင်သည်။',
  'Choose a valid reminder time': 'မှန်ကန်သော သတိပေးချိန် ရွေးပါ။',
  'No customer linked to this debt': 'ဤအကြွေးနှင့် ချိတ်ထားသော ဖောက်သည်မရှိပါ။',
  'Please enter a valid amount': 'မှန်ကန်သော ငွေပမာဏ ထည့်ပါ။',
  'Connect this desktop first': 'ဤကွန်ပျူတာကို Cloud နှင့် အရင်ချိတ်ပါ။',
  'Sync all pending changes before rebuilding local data': 'စက်တွင်းဒေတာ ပြန်လည်မရယူမီ ပို့ရန်ကျန်ဒေတာအားလုံးကို Sync လုပ်ပါ။',
  'Sync all pending changes before removing local data': 'စက်တွင်းဒေတာ မရှင်းမီ ပို့ရန်ကျန်ဒေတာအားလုံးကို Sync လုပ်ပါ။',
  'Sync all pending changes before deleting the cloud account': 'Cloud အကောင့်မဖျက်မီ ပို့ရန်ကျန်ဒေတာအားလုံးကို Sync လုပ်ပါ။',
  'Sync all pending cash activity before closing the drawer': 'ငွေစာရင်းပုံး မပိတ်မီ ကျန်ရှိသော အရောင်းနှင့် ငွေလှုပ်ရှားမှုအားလုံးကို Sync လုပ်ပါ။',
  'Use Disconnect for this desktop': 'ဤကွန်ပျူတာအတွက် “Cloud မှဖြုတ်မည်” ကို သုံးပါ။',
  'Secure OS storage is unavailable': 'စနစ်၏ လုံခြုံသောသိမ်းဆည်းမှုကို အသုံးမပြုနိုင်ပါ။',
  'Secure OS storage is unavailable on this computer': 'ဤကွန်ပျူတာတွင် လုံခြုံသောသိမ်းဆည်းမှုကို အသုံးမပြုနိုင်ပါ။',
  'Install or pair the printer in Windows or macOS first, then choose it in Settings.': 'ပရင်တာကို Windows သို့မဟုတ် macOS တွင် အရင်ချိတ်ပြီး ဆက်တင်ထဲမှ ရွေးပါ။',
  'Printer is unavailable. Reconnect it in macOS Bluetooth settings and try again.': 'ပရင်တာကို အသုံးမပြုနိုင်ပါ။ macOS Bluetooth ဆက်တင်တွင် ပြန်ချိတ်ပြီး ထပ်စမ်းပါ။',
  'USB printer queue is unavailable. Reconnect the cable and find printers again.': 'USB ပရင်တာကို အသုံးမပြုနိုင်ပါ။ ကြိုးပြန်ချိတ်ပြီး ပရင်တာပြန်ရှာပါ။',
  'The printer rejected the receipt': 'ပရင်တာက ဘောင်ချာကို လက်မခံပါ။',
};

const PREFIX_MESSAGES: Array<[string, string]> = [
  ['Product no longer exists: ', 'ကုန်ပစ္စည်း မရှိတော့ပါ — '],
  ['Bluetooth print failed: ', 'Bluetooth ပရင့် မအောင်မြင်ပါ — '],
  ['USB print submission failed: ', 'USB ပရင့် မအောင်မြင်ပါ — '],
  ['Could not read USB printers: ', 'USB ပရင်တာစာရင်း မဖတ်နိုင်ပါ — '],
];

export function myanmarMessage(message: string): string {
  const exact = ERROR_MESSAGES[message];
  if (exact) return exact;
  for (const [prefix, translated] of PREFIX_MESSAGES) {
    if (message.startsWith(prefix)) return translated + message.slice(prefix.length);
  }
  return message;
}
